language: node_js

sudo: false

branches:
  only:
  - hexo

cache:
  - npm

node_js:
  - "10"

before_script:
  - npm install
  - git clone https://github.com/HeskeyBaozi/hexo-theme-lite themes/lite
  - hexo cl

script:
  - hexo generate

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  target-branch: master
  keep-history: false
  on:
    branch: hexo